language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Eyrecraggs
  password:
    secure: JT7brruSfwwt+H4B6NWNkN3RPToBENalKfHzwbAoXWnmHC6/04yQtmsZXdYmd5yLk8QBeh8EhDp2OJi1t/mLnfIyr16KYDp01XPd4EBu8RmfWOrJ0V8Mb7HxnZeNSJpjUdItNXdcty/axZTCDuhu1CISAFgzsf4uozz2bvd9ajzUJA869Uk8uhOvkR39GXyWO3rzhVpGZd9GqdOsPIf1S1r+fWYdAN5qnQHkjWDl+GXaaJBmfrjrbsi/TfDOPARNTcQ7ecLHG742jegNQ/hcQMGY7/jNF0sJzFjwylreoGOOOwi/9IHNafV6Ty7h0V/XpCZjXWutsVXQIpCWb9dNkeyrffbhfa5MHN/+UgU+AQVnVWcJQ9SEj62gGzYcXuSr2Ml+ju8zEb9zZvL+IuI4wWnOylsQ5MrfqGwqRuXMRjEi9Z2ekzb0PXa2D4LXpfyFbjn+UXfNQSUSOrbysJZd5rXBt5lbEB25sQXzQNzKNeuaeQ5D0sKdEof8sC3aCTTnBJexZZ9ZnJfpozH09RrrWhlehuYEuY2N8cU+O1S1jCZnS6jlkYwVRSiX8+4WSXJxCTQSFdxznJNLkYzMZCwGVonu6I4yDxFXhHxRrD1eQTnxry9L0RtApuuobnZKUKRqzZisxz16u089nUr9Pr1sA2Qna48dHeiu+81j99/hPyw=
  on:
    tags: true
    repo: EyreC/file_sort_app
    python: 3.6
